/*
    Nathan Cruz

    NOT COMPLETED NOT EVEN STARTED:
    THE IDEA IS TO ACCESS THE DAMAGE RECEIVER FUNCTION OF PLAYER.CS BUT TO REDUCE THE DAMAGE BEFOREHAND WHEN THIS COLLIDES WITH AN ENEMY PROJECTILE
    MAY NEED SOMETHING ELSE FOR ENEMY ATTACKS (IN THE INSTANCE THE ENEMY ATTACK COLLIDES WITH BOTH SHIELD AND PLAYER BUT THE SHIELD WAS IN LINE OF PATH OF ATTACK)
*/
using UnityEngine;
using System.Collections;

public class Shield : MonoBehaviour {

	void OnEnterCollision2D(Collision2D other)
    {

    }
}
